### PR TITLE
fix(comp): highlights selected rows in PicklistBase

### LINKED ISSUE #445: PicklistBase: Highlight selected rows
Have the selected rows highlighted in some way.  This would include any row that is checked if `useUnits` is `false`, or has a value selected if `useUnits` is true.  

For example:

Image

See the documentation for the Bootstrap Vue Next Table component. The `_rowVariant` attribute on the row might be something that is helpful here.

### PR DESCRIPTION
**Pull request by fejesievo**
**Pull Request Description**

Enables row highlighting on selection

Closes #445 
---

**Licensing Certification**

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request **I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)** for its contents.

Co-authored-by: Niloy Saha <143445417+niloy-saha-123@users.noreply.github.com>

### CODE REVIEW

**Review by braughtg — CHANGES_REQUESTED** [review]
I think that what you have here can be simplified quite a bit.  I would suggest not introducing the new `selectedRows` array and removing all of the related changes.

Then have your code use the existing `pickedRows` array.  The i-th entry in `pickedRows` array indicates whether the i-th row in the table is selected. If units are being used then `pickedRows[i]` is the number selected, and if it is anything greater than 0 the row should be highlighted. If units are not being used then `pickedRows[i]` will be either 0 or 1. So I think you can just have your `getRowClass` method look at `pickedRows` and determine if the row should be highlighted or not then return the appropriate `class` to bind to the row.

You should also undo the changes to the `handleUnitsButton` method because they are not related to this PR.

File: components/PicklistBase/PicklistBase.vue [hunk 1]
```diff
@@ -92,8 +93,9 @@
                 v-bind:name="'picklist-checkbox-' + i"
                 v-bind:key="'checkbox' + i"
                 v-bind:disabled="showOverlay != null"
-                v-bind:checked="pickedRows[i]"
+                v-bind:checked="pickedRows[i] > 0"
```
Comment (braughtg) [inline components/PicklistBase/PicklistBase.vue]: Let's revert this line to what it was before.

File: components/PicklistBase/PicklistBase.vue [hunk 2]
```diff
@@ -92,8 +93,9 @@
...
                 v-on:change="(state) => handleCheckboxChange(i, state)"
+                v-on:click.stop
```
Comment (braughtg) [inline components/PicklistBase/PicklistBase.vue]: Remove this line as it seems to have no effect.

File: components/PicklistBase/PicklistBase.behavior.comp.cy.js [hunk 3]
```diff
@@ -400,4 +400,49 @@ describe('Test the PicklistBase component behavior', () => {
...
+          { name: 'Item 1', quantity: 5, location: 'GHANA' },
+          { name: 'Item 2', quantity: 3, location: 'KENYA' },
+        ],
+        columns: ['name', 'quantity'],
+        labels: { name: 'Name', quantity: 'Quantity', location: 'Location' },
+        picked: new Map(),
+        showInfoIcons: true,
+      },
+    });
+
```
Comment (braughtg) [inline components/PicklistBase/PicklistBase.behavior.comp.cy.js:417]: add check that class is not on the row before the click.

File: components/PicklistBase/PicklistBase.behavior.comp.cy.js [hunk 4]
```diff
@@ -400,4 +400,49 @@ describe('Test the PicklistBase component behavior', () => {
       .find('span')
       .should('contain', '✅ All');
   });
+
+  it('checks that row highlights on event change', () => {
```
Comment (braughtg) [inline components/PicklistBase/PicklistBase.behavior.comp.cy.js]: checks that row highlights when row is selected

File: components/PicklistBase/PicklistBase.behavior.comp.cy.js [hunk 5]
```diff
@@ -400,4 +400,49 @@ describe('Test the PicklistBase component behavior', () => {
...
+    });
+
+    cy.get('[data-cy="picklist-checkbox-0"]').click();
+    cy.get('[data-cy="picklist-row-0"]').should('have.class', 'selected-row');
+
+    cy.get('[data-cy="picklist-checkbox-1"]').click();
+    cy.get('[data-cy="picklist-row-1"]').should('have.class', 'selected-row');
+  });
+
+  it('clears row selection when clicking on the same row', () => {
```
Comment (braughtg) [inline components/PicklistBase/PicklistBase.behavior.comp.cy.js]: highlighting is cleared when row is deselected

File: components/PicklistBase/PicklistBase.behavior.comp.cy.js [hunk 6]
```diff
@@ -400,4 +400,49 @@ describe('Test the PicklistBase component behavior', () => {
...
+        columns: ['name', 'quantity'],
+        labels: { name: 'Name', quantity: 'Quantity', location: 'Location' },
+        picked: new Map(),
+        showInfoIcons: true,
+      },
+    });
+
+    cy.get('[data-cy="picklist-checkbox-0"]').click();
+    cy.get('[data-cy="picklist-row-0"]').should('have.class', 'selected-row');
+
```
Comment (braughtg) [inline components/PicklistBase/PicklistBase.behavior.comp.cy.js:424]: check here too.

**Review by braughtg — CHANGES_REQUESTED** [review]

File: components/PicklistBase/PicklistBase.vue (hunk 1 above)
Comment (fejesievo) [reply components/PicklistBase/PicklistBase.vue]: changed back to original line

File: components/PicklistBase/PicklistBase.vue (hunk 2 above)
Comment (fejesievo) [reply components/PicklistBase/PicklistBase.vue]: removed line

File: components/PicklistBase/PicklistBase.behavior.comp.cy.js (hunk 3 above)
Comment (fejesievo) [reply components/PicklistBase/PicklistBase.behavior.comp.cy.js:417]: added check that class isn't on row first before click

File: components/PicklistBase/PicklistBase.behavior.comp.cy.js (hunk 4 above)
Comment (fejesievo) [reply components/PicklistBase/PicklistBase.behavior.comp.cy.js]: changed it title to "checks that row highlights when row is selected"

File: components/PicklistBase/PicklistBase.behavior.comp.cy.js (hunk 5 above)
Comment (fejesievo) [reply components/PicklistBase/PicklistBase.behavior.comp.cy.js]: changed it title to "highlighting is cleared when row is deselected"
